# Configuración general del sitio
title: mi sitio web 
description:Descripción de mi sitio web 
url://misitioweb.com

# Configuración de los archivos estáticos
static:
dir:public
assets:
-images
-css
-js

# Configuración de páginas
pages:
- title: inicio
patch:/
template: index.html
-title:acerca de 
path:/acerca-de
template:acerca de html

# Cconfiguración de los metadatos 
metadata:
authors:alejandra e lopez 
keywords: sitio web,estatico



