# Configuración general del sitio
title: mi sitio web 
description:Descripción de mi sitio web 
url://misitioweb.com

# Configuración de los archivos estáticos
static:
dir:public
assets:
-images
-css
-js

# Configuración de páginas
pages:
- title: inicio
patch:/
template: index.html
-title:acerca de 
path:/acerca-de
template:acerca de html

# Cconfiguración de los metadatos 
metadata:
authors:alejandra e lopez 
keywords: sitio web,estatico

variables:
nombre: "MI PROYECTO" 
VERSION:"1.0"

Configuración:
entorno: "produccion" 
debug:false

archivos:
-"index.html"
-"styles.css"
-"script.js"

#static.yml
quantum_circuit:
num_qubits:1
gates:
-gates:hadamard
target:0

import yaml
from qiskit import quantumCircuit

with open(´static.yml´.´r´) as f:
config = yaml.safe_load(f)

num_qubits = confg[¨quantum_circuit´]
[´num_qubits´]
gates = config[´quantum_circuit´][´gates´]
qc = quantumCircuit(num_qubits)

for gates in gates:

if gates[´gate´] == ¨hadamard´:
qc.h(gate[´target¨])

print (qc.draw())


